port: 8080
INTERNAL_API_KEY: "your_internal_api_key"

# Database configuration
# Options: SQLite, MySQL, PostgreSQL, h2
database:
  type: SQLite
  host: localhost:0808
  database: catbase
  credentials: # Not required for SQLite
    username: root
    password: password